// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: Reactive-Welfare-Housing-System/src/messages/shared.proto

package sharedMessages

import (
	actor "github.com/AsynkronIT/protoactor-go/actor"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NewHouses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Houses []*NewHouse `protobuf:"bytes,1,rep,name=Houses,proto3" json:"Houses,omitempty"`
}

func (x *NewHouses) Reset() {
	*x = NewHouses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewHouses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewHouses) ProtoMessage() {}

func (x *NewHouses) ProtoReflect() protoreflect.Message {
	mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewHouses.ProtoReflect.Descriptor instead.
func (*NewHouses) Descriptor() ([]byte, []int) {
	return file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescGZIP(), []int{0}
}

func (x *NewHouses) GetHouses() []*NewHouse {
	if x != nil {
		return x.Houses
	}
	return nil
}

type NewHouse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Level int32 `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
	Age   int32 `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
	Area  int32 `protobuf:"varint,4,opt,name=Area,proto3" json:"Area,omitempty"`
}

func (x *NewHouse) Reset() {
	*x = NewHouse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewHouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewHouse) ProtoMessage() {}

func (x *NewHouse) ProtoReflect() protoreflect.Message {
	mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewHouse.ProtoReflect.Descriptor instead.
func (*NewHouse) Descriptor() ([]byte, []int) {
	return file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescGZIP(), []int{1}
}

func (x *NewHouse) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *NewHouse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *NewHouse) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *NewHouse) GetArea() int32 {
	if x != nil {
		return x.Area
	}
	return 0
}

type ManagerConnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender *actor.PID `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
}

func (x *ManagerConnect) Reset() {
	*x = ManagerConnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagerConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerConnect) ProtoMessage() {}

func (x *ManagerConnect) ProtoReflect() protoreflect.Message {
	mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerConnect.ProtoReflect.Descriptor instead.
func (*ManagerConnect) Descriptor() ([]byte, []int) {
	return file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescGZIP(), []int{2}
}

func (x *ManagerConnect) GetSender() *actor.PID {
	if x != nil {
		return x.Sender
	}
	return nil
}

type DistributorConnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender *actor.PID `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
}

func (x *DistributorConnect) Reset() {
	*x = DistributorConnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistributorConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributorConnect) ProtoMessage() {}

func (x *DistributorConnect) ProtoReflect() protoreflect.Message {
	mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributorConnect.ProtoReflect.Descriptor instead.
func (*DistributorConnect) Descriptor() ([]byte, []int) {
	return file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescGZIP(), []int{3}
}

func (x *DistributorConnect) GetSender() *actor.PID {
	if x != nil {
		return x.Sender
	}
	return nil
}

type ExaminationList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HouseID []int32 `protobuf:"varint,1,rep,packed,name=HouseID,proto3" json:"HouseID,omitempty"`
}

func (x *ExaminationList) Reset() {
	*x = ExaminationList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExaminationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExaminationList) ProtoMessage() {}

func (x *ExaminationList) ProtoReflect() protoreflect.Message {
	mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExaminationList.ProtoReflect.Descriptor instead.
func (*ExaminationList) Descriptor() ([]byte, []int) {
	return file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescGZIP(), []int{4}
}

func (x *ExaminationList) GetHouseID() []int32 {
	if x != nil {
		return x.HouseID
	}
	return nil
}

type VerifierConnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender *actor.PID `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
}

func (x *VerifierConnect) Reset() {
	*x = VerifierConnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifierConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifierConnect) ProtoMessage() {}

func (x *VerifierConnect) ProtoReflect() protoreflect.Message {
	mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifierConnect.ProtoReflect.Descriptor instead.
func (*VerifierConnect) Descriptor() ([]byte, []int) {
	return file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescGZIP(), []int{5}
}

func (x *VerifierConnect) GetSender() *actor.PID {
	if x != nil {
		return x.Sender
	}
	return nil
}

type NewRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*NewRequest `protobuf:"bytes,1,rep,name=Requests,proto3" json:"Requests,omitempty"`
}

func (x *NewRequests) Reset() {
	*x = NewRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRequests) ProtoMessage() {}

func (x *NewRequests) ProtoReflect() protoreflect.Message {
	mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRequests.ProtoReflect.Descriptor instead.
func (*NewRequests) Descriptor() ([]byte, []int) {
	return file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescGZIP(), []int{6}
}

func (x *NewRequests) GetRequests() []*NewRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type NewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FamilyID int32 `protobuf:"varint,1,opt,name=FamilyID,proto3" json:"FamilyID,omitempty"`
	Level    int32 `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
}

func (x *NewRequest) Reset() {
	*x = NewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRequest) ProtoMessage() {}

func (x *NewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRequest.ProtoReflect.Descriptor instead.
func (*NewRequest) Descriptor() ([]byte, []int) {
	return file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescGZIP(), []int{7}
}

func (x *NewRequest) GetFamilyID() int32 {
	if x != nil {
		return x.FamilyID
	}
	return 0
}

func (x *NewRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type NewCheckOuts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckOuts []*NewCheckOut `protobuf:"bytes,1,rep,name=CheckOuts,proto3" json:"CheckOuts,omitempty"`
}

func (x *NewCheckOuts) Reset() {
	*x = NewCheckOuts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewCheckOuts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCheckOuts) ProtoMessage() {}

func (x *NewCheckOuts) ProtoReflect() protoreflect.Message {
	mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCheckOuts.ProtoReflect.Descriptor instead.
func (*NewCheckOuts) Descriptor() ([]byte, []int) {
	return file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescGZIP(), []int{8}
}

func (x *NewCheckOuts) GetCheckOuts() []*NewCheckOut {
	if x != nil {
		return x.CheckOuts
	}
	return nil
}

type NewCheckOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FamilyID int32 `protobuf:"varint,1,opt,name=FamilyID,proto3" json:"FamilyID,omitempty"`
	Level    int32 `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
}

func (x *NewCheckOut) Reset() {
	*x = NewCheckOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewCheckOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCheckOut) ProtoMessage() {}

func (x *NewCheckOut) ProtoReflect() protoreflect.Message {
	mi := &file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCheckOut.ProtoReflect.Descriptor instead.
func (*NewCheckOut) Descriptor() ([]byte, []int) {
	return file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescGZIP(), []int{9}
}

func (x *NewCheckOut) GetFamilyID() int32 {
	if x != nil {
		return x.FamilyID
	}
	return 0
}

func (x *NewCheckOut) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_Reactive_Welfare_Housing_System_src_messages_shared_proto protoreflect.FileDescriptor

var file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDesc = []byte{
	0x0a, 0x39, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x2d, 0x57, 0x65, 0x6c, 0x66, 0x61,
	0x72, 0x65, 0x2d, 0x48, 0x6f, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x2d, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x1a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x41, 0x73, 0x79, 0x6e, 0x6b, 0x72, 0x6f, 0x6e, 0x49, 0x54, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x09, 0x4e,
	0x65, 0x77, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x2e, 0x4e, 0x65, 0x77, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x06, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x73, 0x22, 0x56, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x41, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x72, 0x65, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x41, 0x72, 0x65, 0x61, 0x22, 0x34, 0x0a, 0x0e, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x22, 0x0a, 0x06,
	0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x22, 0x38, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x6f, 0x72, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x22, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50,
	0x49, 0x44, 0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x2b, 0x0a, 0x0f, 0x45, 0x78,
	0x61, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07,
	0x48, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x44, 0x22, 0x35, 0x0a, 0x0f, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x22, 0x0a, 0x06, 0x53, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x3d,
	0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x2e, 0x0a,
	0x08, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x08, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x3e, 0x0a,
	0x0a, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x46,
	0x61, 0x6d, 0x69, 0x6c, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x46,
	0x61, 0x6d, 0x69, 0x6c, 0x79, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x41, 0x0a,
	0x0c, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x73, 0x12, 0x31, 0x0a,
	0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x73,
	0x22, 0x3f, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x42, 0x3d, 0x5a, 0x3b, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x2d, 0x57, 0x65,
	0x6c, 0x66, 0x61, 0x72, 0x65, 0x2d, 0x48, 0x6f, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x2d, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescOnce sync.Once
	file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescData = file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDesc
)

func file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescGZIP() []byte {
	file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescOnce.Do(func() {
		file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescData = protoimpl.X.CompressGZIP(file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescData)
	})
	return file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDescData
}

var file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_Reactive_Welfare_Housing_System_src_messages_shared_proto_goTypes = []interface{}{
	(*NewHouses)(nil),          // 0: shared.NewHouses
	(*NewHouse)(nil),           // 1: shared.NewHouse
	(*ManagerConnect)(nil),     // 2: shared.ManagerConnect
	(*DistributorConnect)(nil), // 3: shared.DistributorConnect
	(*ExaminationList)(nil),    // 4: shared.ExaminationList
	(*VerifierConnect)(nil),    // 5: shared.VerifierConnect
	(*NewRequests)(nil),        // 6: shared.NewRequests
	(*NewRequest)(nil),         // 7: shared.NewRequest
	(*NewCheckOuts)(nil),       // 8: shared.NewCheckOuts
	(*NewCheckOut)(nil),        // 9: shared.NewCheckOut
	(*actor.PID)(nil),          // 10: actor.PID
}
var file_Reactive_Welfare_Housing_System_src_messages_shared_proto_depIdxs = []int32{
	1,  // 0: shared.NewHouses.Houses:type_name -> shared.NewHouse
	10, // 1: shared.ManagerConnect.Sender:type_name -> actor.PID
	10, // 2: shared.DistributorConnect.Sender:type_name -> actor.PID
	10, // 3: shared.VerifierConnect.Sender:type_name -> actor.PID
	7,  // 4: shared.NewRequests.Requests:type_name -> shared.NewRequest
	9,  // 5: shared.NewCheckOuts.CheckOuts:type_name -> shared.NewCheckOut
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_Reactive_Welfare_Housing_System_src_messages_shared_proto_init() }
func file_Reactive_Welfare_Housing_System_src_messages_shared_proto_init() {
	if File_Reactive_Welfare_Housing_System_src_messages_shared_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewHouses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewHouse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagerConnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistributorConnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExaminationList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifierConnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewCheckOuts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewCheckOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Reactive_Welfare_Housing_System_src_messages_shared_proto_goTypes,
		DependencyIndexes: file_Reactive_Welfare_Housing_System_src_messages_shared_proto_depIdxs,
		MessageInfos:      file_Reactive_Welfare_Housing_System_src_messages_shared_proto_msgTypes,
	}.Build()
	File_Reactive_Welfare_Housing_System_src_messages_shared_proto = out.File
	file_Reactive_Welfare_Housing_System_src_messages_shared_proto_rawDesc = nil
	file_Reactive_Welfare_Housing_System_src_messages_shared_proto_goTypes = nil
	file_Reactive_Welfare_Housing_System_src_messages_shared_proto_depIdxs = nil
}
