// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.12.0
// source: Reactive-Welfare-Housing-System/src/messages/manager.proto

package managerMessages

import (
	distributorMessages "Reactive-Welfare-Housing-System/src/messages/distributorMessages"
	_ "github.com/AsynkronIT/protoactor-go/actor"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type HouseMatchApprove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Match *distributorMessages.HouseMatch `protobuf:"bytes,1,opt,name=Match,proto3" json:"Match,omitempty"`
}

func (x *HouseMatchApprove) Reset() {
	*x = HouseMatchApprove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Reactive_Welfare_Housing_System_src_messages_manager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseMatchApprove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseMatchApprove) ProtoMessage() {}

func (x *HouseMatchApprove) ProtoReflect() protoreflect.Message {
	mi := &file_Reactive_Welfare_Housing_System_src_messages_manager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseMatchApprove.ProtoReflect.Descriptor instead.
func (*HouseMatchApprove) Descriptor() ([]byte, []int) {
	return file_Reactive_Welfare_Housing_System_src_messages_manager_proto_rawDescGZIP(), []int{0}
}

func (x *HouseMatchApprove) GetMatch() *distributorMessages.HouseMatch {
	if x != nil {
		return x.Match
	}
	return nil
}

var File_Reactive_Welfare_Housing_System_src_messages_manager_proto protoreflect.FileDescriptor

var file_Reactive_Welfare_Housing_System_src_messages_manager_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x2d, 0x57, 0x65, 0x6c, 0x66, 0x61,
	0x72, 0x65, 0x2d, 0x48, 0x6f, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x2d, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x1a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x41, 0x73, 0x79, 0x6e, 0x6b, 0x72, 0x6f, 0x6e, 0x49, 0x54, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x3e, 0x52,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x2d, 0x57, 0x65, 0x6c, 0x66, 0x61, 0x72, 0x65, 0x2d,
	0x48, 0x6f, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x2d, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x73,
	0x72, 0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a,
	0x11, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x6f, 0x72, 0x2e,
	0x48, 0x6f, 0x75, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x05, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x42, 0x3e, 0x5a, 0x3c, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x2d, 0x57, 0x65,
	0x6c, 0x66, 0x61, 0x72, 0x65, 0x2d, 0x48, 0x6f, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x2d, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Reactive_Welfare_Housing_System_src_messages_manager_proto_rawDescOnce sync.Once
	file_Reactive_Welfare_Housing_System_src_messages_manager_proto_rawDescData = file_Reactive_Welfare_Housing_System_src_messages_manager_proto_rawDesc
)

func file_Reactive_Welfare_Housing_System_src_messages_manager_proto_rawDescGZIP() []byte {
	file_Reactive_Welfare_Housing_System_src_messages_manager_proto_rawDescOnce.Do(func() {
		file_Reactive_Welfare_Housing_System_src_messages_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_Reactive_Welfare_Housing_System_src_messages_manager_proto_rawDescData)
	})
	return file_Reactive_Welfare_Housing_System_src_messages_manager_proto_rawDescData
}

var file_Reactive_Welfare_Housing_System_src_messages_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Reactive_Welfare_Housing_System_src_messages_manager_proto_goTypes = []interface{}{
	(*HouseMatchApprove)(nil),              // 0: manager.HouseMatchApprove
	(*distributorMessages.HouseMatch)(nil), // 1: distributor.HouseMatch
}
var file_Reactive_Welfare_Housing_System_src_messages_manager_proto_depIdxs = []int32{
	1, // 0: manager.HouseMatchApprove.Match:type_name -> distributor.HouseMatch
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Reactive_Welfare_Housing_System_src_messages_manager_proto_init() }
func file_Reactive_Welfare_Housing_System_src_messages_manager_proto_init() {
	if File_Reactive_Welfare_Housing_System_src_messages_manager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Reactive_Welfare_Housing_System_src_messages_manager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseMatchApprove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Reactive_Welfare_Housing_System_src_messages_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Reactive_Welfare_Housing_System_src_messages_manager_proto_goTypes,
		DependencyIndexes: file_Reactive_Welfare_Housing_System_src_messages_manager_proto_depIdxs,
		MessageInfos:      file_Reactive_Welfare_Housing_System_src_messages_manager_proto_msgTypes,
	}.Build()
	File_Reactive_Welfare_Housing_System_src_messages_manager_proto = out.File
	file_Reactive_Welfare_Housing_System_src_messages_manager_proto_rawDesc = nil
	file_Reactive_Welfare_Housing_System_src_messages_manager_proto_goTypes = nil
	file_Reactive_Welfare_Housing_System_src_messages_manager_proto_depIdxs = nil
}
